apiVersion: batch/v1
kind: Job
metadata:
  name: artillery
spec:
  template:
    metadata:
      name: artillery
    spec:
      containers:
      - name: art
        image: gcr.io/kube-226720/artillery:latest
        args: ["run /artillery/vote.yaml"]
      restartPolicy: Never
